### ISSUE TITLE
SSR hydration causes 'Failed attempt to create new DOM elements during hydration'

### ISSUE THREAD

**Issue by asaf** [solidjs/solid-docs-next#375]
### Describe the bug

I'm trying to hydrate a component in the client but the following error occurs:

```bash
Uncaught (in promise) Error: Failed attempt to create new DOM elements during hydration. Check that the libraries you are using support hydration.
    at create (dev.js:124:37)
    at fn (dev.js:129:120)
    at dev.js:22:20
    at Hello (dev.js:25:7)
    at dev.js:552:12
    at untrack (dev.js:442:12)
    at Object.fn (dev.js:548:37)
    at runComputation (dev.js:698:22)
    at updateComputation (dev.js:681:3)
    at devComponent (dev.js:559:3)
```

Notes: 
- With v1.7.12 SSR renders the component then hydration cleans it up.
- This only happens when I try to import a component from another package (in this case the 'hello' package) which is built using tsup and [tsup-preset-solid](https://github.com/solidjs-community/tsup-preset-solid)

Best,
Asaf.

### Your Example Website or App

https://stackblitz.com/edit/github-xfquhi
https://github.com/asaf/solidjs-ssr

### Steps to Reproduce the Bug or Issue

1. Clone  repo https://github.com/asaf/solidjs-ssr
2. pnpm i
3. pnpm dev
4. open browser http://localhost:3009/foo

### Expected behavior

Component should be hydrated

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.8.5

**Comment by asaf** [comment]
Thanks for answering,

Have you had a chance to look at my sample? I used [tsup-preset-solid](https://github.com/solidjs-community/tsup-preset-solid) which is able to produce different client / server code and I have a `node` entry in the `exports` section and it also adds [solid export condition](https://github.com/solidjs-community/tsup-preset-solid#usage-gotchas).
