### ISSUE TITLE
[Bug]: Pagination error crashes first and last page of each Reference

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-docs-next#623]
### 📝 Issue Description

When navigating the reference, some pages ocationally crash with 404's

### 📋 On which page(s) it occurs

The top and bottom page in each Reference section.

**Repro**
If I somewhat fast alternate between clicking i.e. the first and second page in the reference section, it'll crash after a few clicks (often < 10). Could seem like some async logic can't keep up, or something is accumulating, idk.

https://github.com/solidjs/solid-docs-next/assets/74932975/2f83f0f1-d86f-48f7-b940-63036c2bbb7b

### 🤔 Expected Behavior

That the pages load

### 👀 Current Behavior

It crashes with a 404, and this strange error about pagination from the top page:

```
chunk-3E67F7F4.js?v=01630017:1559 TypeError: Cannot read properties of null (reading 'path')
    at get href (pagination.tsx:47:22)
    at external (i18n-anchor.tsx:16:45)
    at get when (i18n-anchor.tsx:36:17)
    at Switch.createMemo.equals.equals [as fn] (chunk-3E67F7F4.js?v=01630017:1515:28)
    at runComputation (chunk-3E67F7F4.js?v=01630017:707:22)
    at updateComputation (chunk-3E67F7F4.js?v=01630017:689:3)
    at runTop (chunk-3E67F7F4.js?v=01630017:798:7)
    at runQueue (chunk-3E67F7F4.js?v=01630017:869:42)
    at completeUpdates (chunk-3E67F7F4.js?v=01630017:825:84)
    at runUpdates (chunk-3E67F7F4.js?v=01630017:815:5)
ErrorBoundary.createMemo.name @ chunk-3E67F7F4.js?v=01630017:1559
Show 1 more frame
Show less
```

### 🖥️ Browser

Chrome 122

**Comment by birkskyum** [comment]
I've made a PR (#625) with a fix for this issue, which is awaiting review.
